com:
  niaobulashi:
    title: niaobulashi
    description: \u9E1F\u4E0D\u62C9\u5C4E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
