com:
  niaobulashi:
    title: niaobulashi
    description: javaDemo
server:
  port: 9001
  servlet:
    context-path: /niaobulashi

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
